name: Android Debug Build

# Trigger workflow on push or pull request to any branch
on:
  push:
    branches:
      - '**'   # all branches
  pull_request:
    branches:
      - '**'   # all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Setup JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Setup Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Step 4: Build debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 5: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
